### PR TITLE
CI: migrate from Travis-CI to GitHub Actions

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Review by cosmo0920 — APPROVED** [review]
LGTM! Thank you.

**Review by cosmo0920 — CHANGES_REQUESTED** [review]
Ah, I've overlooked GitHub Actions failures on Windows and macOS.
https://github.com/kenhys/fluent-plugin-redis/actions?query=workflow%3A%22Testing+on+Windows%22
@kenhys Could you take a look?

**Comment by cosmo0920** [comment]
If you couldn't find how to resolve GitHub Actions failures on Windows and macOS, only Linux testing is OK for us.

**Comment by kenhys** [comment]
services: seems only available on linux.

**Review by cosmo0920 — APPROVED** [review]

**Pull request merged**
