### PR TITLE
Execute test cases

### PR DESCRIPTION
**Pull request by cosmo0920**
Hi, @yuki24 !

I've tried to execute test cases with current development version of Fluentd (0.14.9).
It is welcomed to come back current Fluentd world this plugin.
Could you consider to review this patch?

Best regards,

### CODE REVIEW

**Comment by yuki24** [comment]
@cosmo0920 I don't think I can maintain this project now as I haven't used fluentd these days. Are you interested in taking over the project?

**Comment by cosmo0920** [comment]
Yes, I am.
I want to take over this project.
Could you transfer ownership into [fluent-plugins-nursery organization](https://github.com/fluent-plugins-nursery) and plugin author adds @okkez to Gem owner?

**Comment by yuki24** [comment]
This seems a little tricky - I tried to transfer the ownership to the org but got rejected since I don't have admin rights to it. I also tried to transfer to you but got rejected again because you already have a fork of this repo. However, I was able to send a transfer request to @okkez and he should be able to transfer to the org once he accepts it.

Let me know if there's anything I can help. Thanks!

**Comment by okkez** [comment]
Thank you!
@yuki24 Could you run following command:
```
gem owner fluent-plugin-redis -a okkez000@gmail.com
```

**Comment by yuki24** [comment]
@okkez I've added you to the rubygem project as an owner and you should be able to push now.

**Comment by okkez** [comment]
Thank you for quick response!

**Pull request merged**
